theme = "custom"
mode = "auto"
line_numbers = true
wrap_lines = false

[custom_theme]
base = "graphite"
label = "Poimandres"
background = "#252b37"
panel = "#252b37"
panelAlt = "#303340"
border = "#506477"
accent = "#89ddff"
accentMuted = "#42675a"
text = "#e4f0fb"
muted = "#a6accd"
addedBg = "#203a38"
removedBg = "#3a2435"
contextBg = "#252b37"
addedContentBg = "#284f49"
removedContentBg = "#4f2d43"
contextContentBg = "#252b37"
addedSignColor = "#5de4c7"
removedSignColor = "#d0679d"
lineNumberBg = "#252b37"
lineNumberFg = "#767c9d"
selectedHunk = "#717cb4"
badgeAdded = "#5de4c7"
badgeRemoved = "#d0679d"
badgeNeutral = "#a6accd"
fileNew = "#5de4c7"
fileDeleted = "#d0679d"
fileRenamed = "#fffac2"
fileModified = "#fcc5e9"
fileUntracked = "#89ddff"
noteBorder = "#fcc5e9"
noteBackground = "#252337"
noteTitleBackground = "#303340"
noteTitleText = "#ffffff"

[custom_theme.syntax]
default = "#e4f0fb"
keyword = "#ffffff"
string = "#5de4c7"
comment = "#767c9d"
number = "#fffac2"
function = "#89ddff"
property = "#add7ff"
type = "#fcc5e9"
punctuation = "#a6accd"
