require("jason.plugins-setup")

require("jason.core.options")
require("jason.core.keymaps")
require("jason.core.colorscheme")
require("jason.core.colorscheme")

require("jason.plugins.comment")
require("jason.plugins.gitsigns")
require("jason.plugins.leap")
require("jason.plugins.lualine")
require("jason.plugins.neoscroll")
require("jason.plugins.nvim-cmp")
require("jason.plugins.nvim-tree")
require("jason.plugins.telescope")
require("jason.plugins.toggleterm")
require("jason.plugins.treesitter")
require("jason.plugins.autopairs")
require("jason.plugins.do")

require("jason.plugins.lsp.mason")
require("jason.plugins.lsp.lspsaga")
require("jason.plugins.lsp.lspconfig")
require("jason.plugins.lsp.null-ls")
