set -g RELOAD_PROTECTED_ENV_VARS \
    COLORTERM \
    DISPLAY \
    HOME \
    PWD \
    SHELL \
    SSH_AGENT_PID \
    SSH_AUTH_SOCK \
    TERM \
    VSCODE_GIT_IPC_HANDLE \
    VTE_VERSION \
    XAUTHORITY \
    XDG_RUNTIME_DIR \
    ZELLIJ \
    ZELLIJ_SESSION_NAME
